- hosts: all
  become: yes
  tasks:
  - name: Copia file network/interfaces in router
    become: yes
    ansible.builtin.copy:
      src: <path sorgente>
      dest: /etc/network/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Installa dnsmasq
    become: yes
    apt:
      name: dnsmasq
      state: latest
      update_cache: yes
  - name: Copia di sysctl.conf in router
    become: yes
    ansible.builtin.copy:
      src: <path sorgente>
      dest: /etc/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Copia di dnsmasq.conf in router
    become: yes
    ansible.builtin.copy:
      src: <path sorgente>
      dest: /etc/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Cambia hostname
    become: yes
    ansible.builtin.hostname:
      name: Router1
