- hosts: all
  become: yes
  tasks:
  - name: Copia file network/interfaces in router
    become: yes
    ansible.builtin.copy:
      src: /home/umberto/Scrivania/file_per_esame_LAS/file_config/router/interfaces
      dest: /etc/network/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Installa dnsmasq
    become: yes
    apt:
      name: dnsmasq
      state: latest
      update_cache: yes
  - name: Copia di sysctl.conf in router
    become: yes
    ansible.builtin.copy:
      src: /home/umberto/Scrivania/file_per_esame_LAS/file_config/router/sysctl.conf
      dest: /etc/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Copia di dnsmasq.conf in router
    become: yes
    ansible.builtin.copy:
      src: /home/umberto/Scrivania/file_per_esame_LAS/file_config/router/dnsmasq.conf
      dest: /etc/
      owner: vagrant
      group: vagrant
      mode: '0600'
  - name: Cambia hostname
    become: yes
    ansible.builtin.hostname:
      name: Router1
  - name: Installazione snmpd
    become: yes
    apt:
      name: snmpd
      state: latest
      update_cache: yes
  - name: Copia di snmp.conf su agent
    become: yes
    ansible.builtin.copy:
      src: /home/umberto/Scrivania/file_per_esame_LAS/file_config/snmpd.conf
      dest: /etc/snmpd/
      owner: vagrant
      group: vagrant
      mode: '0600'
